import { EvaluationCorpusSchema, type EvaluationCorpus } from "./schemas";

const corpus = {
  version: "1",
  scenarios: [
    {
      id: "ai-logo-creator",
      title: "AI logo creator with authentication and free credits",
      initialIdea:
        "An AI logo creator for startups: a founder writes a brand brief, gets logo concepts, and can use free credits. The team prefers Next.js and may use Clerk authentication.",
      answers: [
        "Startup founders and small business owners are the first users.",
        "The core flow is to enter a brand brief, generate logo concepts, select a concept, and export a PNG.",
        "AI generates the logo concepts from the brand brief. Free credits limit the number of generations.",
        "The team prefers Next.js and Clerk, but those preferences are not confirmed yet.",
        "Accounts, credit balances, and generated logo history may need database persistence.",
      ],
      facts: [
        {
          id: "logo-problem",
          statement:
            "Startup founders need a fast way to generate usable logo concepts without hiring a designer.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "logo-users",
          statement: "Startup founders and small business owners are the first users.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "logo-goal",
          statement: "V1 must let a user generate and export logo concepts.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "logo-credits",
          statement: "Free credits limit the number of logo generations.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "logo-flow",
          statement:
            "The core flow is entering a brand brief, generating logo concepts, selecting a concept, and exporting a PNG.",
          source: "explicit",
          topic: "core-flows",
        },
        {
          id: "logo-ai",
          statement: "AI generates logo concepts from a brand brief.",
          source: "explicit",
          topic: "ai",
        },
        {
          id: "logo-auth",
          statement: "The team prefers Clerk authentication, but it is not confirmed for V1.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "logo-framework",
          statement: "The team prefers Next.js for the web interface, but it is not confirmed.",
          source: "explicit",
          topic: "other",
        },
        {
          id: "logo-persistence",
          statement: "Accounts, credit balances, and generated logo history may need database persistence.",
          source: "explicit",
          topic: "persistence",
        },
        {
          id: "logo-domain",
          statement: "The domain includes brand briefs, logo generations, exported assets, and credit balances.",
          source: "explicit",
          topic: "domain",
        },
        {
          id: "logo-ui",
          statement: "The UI should make the brand brief, generation gallery, credits, and export action visible.",
          source: "explicit",
          topic: "ui",
        },
        {
          id: "logo-testing",
          statement: "Verify generation limits, export validity, and the main logo workflow.",
          source: "explicit",
          topic: "testing",
        },
      ],
      expectations: {
        requiredFactPatterns: ["logo", "brand brief", "free credits", "Next.js", "Clerk"],
        materialGapTopics: [],
        forbiddenGapTopics: [],
        requiredSections: [
          { section: "product", patterns: ["logo"] },
          { section: "goals", patterns: ["generate", "logo"] },
          { section: "stack", patterns: ["next.js", "clerk"] },
          { section: "domain", patterns: ["brand brief", "logo"] },
          { section: "ai", patterns: ["logo"] },
          { section: "features", patterns: ["generate", "logo", "brand brief", "export"] },
        ],
        requiredStackDecisions: [
          {
            categoryPattern: "web framework",
            choicePattern: "next.js",
            statusMustNotBe: "confirmed",
          },
          {
            categoryPattern: "authentication",
            choicePattern: "clerk",
            statusMustNotBe: "confirmed",
          },
        ],
        prohibitedBlueprintPatterns: ["must use blockchain"],
        requireAiSection: true,
        expectedReady: true,
        contradictionMustBlock: false,
      },
    },
    {
      id: "local-timer",
      title: "Simple local-only utility",
      initialIdea: "A local-only focus timer for one person, with no account and no database.",
      answers: [
        "The user starts, pauses, and resets a focus session.",
        "Sessions can remain in browser memory for V1.",
      ],
      facts: [
        {
          id: "timer-problem",
          statement: "A person needs a distraction-free focus timer.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "timer-user",
          statement: "The first user is one person using the timer locally.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "timer-scope",
          statement: "V1 must start, pause, resume, and reset a focus session.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "timer-persistence",
          statement: "V1 is local-only, keeps session state in-memory, and does not use a database.",
          source: "explicit",
          topic: "persistence",
        },
        {
          id: "timer-auth",
          statement: "V1 does not require authentication or accounts.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "timer-flow",
          statement: "The core flow is starting, pausing, and resetting a timer.",
          source: "explicit",
          topic: "core-flows",
        },
      ],
      expectations: {
        requiredFactPatterns: ["local-only", "in-memory", "does not use a database"],
        materialGapTopics: [],
        forbiddenGapTopics: ["ai", "authentication", "persistence"],
        requiredSections: [
          { section: "product", patterns: ["focus timer"] },
          { section: "goals", patterns: ["timer"] },
          { section: "features", patterns: ["timer"] },
        ],
        requiredStackDecisions: [],
        prohibitedBlueprintPatterns: ["invented billing", "mandatory ai provider"],
        requireAiSection: false,
        expectedReady: true,
        contradictionMustBlock: false,
      },
    },
    {
      id: "b2b-workspace",
      title: "B2B application with roles and organization isolation",
      initialIdea: "A B2B workspace where organizations manage projects with role-based access.",
      answers: [
        "Organization admins invite members and assign roles.",
        "Each organization must only see its own projects.",
        "Use authentication and durable database storage in V1.",
      ],
      facts: [
        {
          id: "b2b-problem",
          statement: "Organizations need a shared project workspace with controlled access.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "b2b-users",
          statement: "Organization admins and members are the first users.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "b2b-scope",
          statement: "V1 must create projects, invite members, and manage roles.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "b2b-roles",
          statement: "Admins manage membership and members work within assigned roles.",
          source: "explicit",
          topic: "user-roles",
        },
        {
          id: "b2b-auth",
          statement: "V1 requires authenticated organization members.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "b2b-persistence",
          statement: "Projects, memberships, and roles require database persistence.",
          source: "explicit",
          topic: "persistence",
        },
        {
          id: "b2b-security",
          statement: "Organization isolation must prevent cross-tenant project access.",
          source: "explicit",
          topic: "security",
        },
        {
          id: "b2b-flow",
          statement: "The core flow is inviting a member, assigning a role, and accessing an organization project.",
          source: "explicit",
          topic: "core-flows",
        },
      ],
      expectations: {
        requiredFactPatterns: ["organization", "role", "isolation", "database"],
        materialGapTopics: [],
        forbiddenGapTopics: [],
        requiredSections: [
          { section: "users", patterns: ["admin", "member"] },
          { section: "security", patterns: ["organization", "isolation"] },
          { section: "domain", patterns: ["project", "role"] },
          { section: "features", patterns: ["invite", "role"] },
        ],
        requiredStackDecisions: [
          {
            categoryPattern: "persistence",
            choicePattern: "database",
          },
        ],
        prohibitedBlueprintPatterns: ["invented anonymous access"],
        requireAiSection: false,
        expectedReady: true,
        contradictionMustBlock: false,
      },
    },
    {
      id: "human-approved-ai-workflow",
      title: "AI-assisted workflow with mandatory human approval",
      initialIdea: "An AI assistant drafts customer support replies, but a human must approve every reply.",
      answers: [
        "Support agents review the draft, edit it, and explicitly approve sending.",
        "The assistant must never send a reply without approval.",
      ],
      facts: [
        {
          id: "approval-problem",
          statement: "Support agents need help drafting accurate customer replies.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "approval-user",
          statement: "Support agents are the first users.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "approval-scope",
          statement: "V1 must draft a support reply for an agent to review and send.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "approval-ai",
          statement: "AI drafts replies from the customer conversation and support context.",
          source: "explicit",
          topic: "ai",
        },
        {
          id: "approval-boundary",
          statement: "A human must approve every reply before it is sent.",
          source: "explicit",
          topic: "human-approval",
        },
        {
          id: "approval-security",
          statement: "The assistant must never send a reply without human approval.",
          source: "explicit",
          topic: "security",
        },
        {
          id: "approval-auth",
          statement: "V1 requires authenticated support agents.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "approval-persistence",
          statement: "Drafts can remain in-memory during V1.",
          source: "explicit",
          topic: "persistence",
        },
      ],
      expectations: {
        requiredFactPatterns: ["AI", "human", "approve", "never send"],
        materialGapTopics: [],
        forbiddenGapTopics: [],
        requiredSections: [
          { section: "ai", patterns: ["draft", "approval"] },
          { section: "security", patterns: ["approval"] },
          { section: "features", patterns: ["reply"] },
        ],
        requiredStackDecisions: [],
        prohibitedBlueprintPatterns: ["send automatically"],
        requireAiSection: true,
        expectedReady: true,
        contradictionMustBlock: false,
      },
    },
    {
      id: "unconfirmed-stack-preferences",
      title: "Existing stack preferences that must remain unconfirmed",
      initialIdea: "A small project dashboard; the team prefers Next.js and Clerk but has not chosen them.",
      answers: [
        "The dashboard shows project status to a small internal team.",
        "Framework and authentication remain open choices for architecture review.",
      ],
      facts: [
        {
          id: "preference-problem",
          statement: "A small internal team needs a clear project status dashboard.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "preference-user",
          statement: "Internal project coordinators are the first users.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "preference-scope",
          statement: "V1 must show project status and recent updates.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "preference-framework",
          statement: "The team prefers Next.js, but the framework is not confirmed.",
          source: "explicit",
          topic: "other",
        },
        {
          id: "preference-auth",
          statement: "The team prefers Clerk, but authentication is not confirmed.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "preference-persistence",
          statement: "Persistence is unresolved and must not be installed by default.",
          source: "explicit",
          topic: "persistence",
        },
      ],
      expectations: {
        requiredFactPatterns: ["prefers Next.js", "prefers Clerk", "not confirmed"],
        materialGapTopics: [],
        forbiddenGapTopics: [],
        requiredSections: [
          { section: "product", patterns: ["dashboard"] },
          { section: "features", patterns: ["status"] },
        ],
        requiredStackDecisions: [
          {
            categoryPattern: "web framework",
            choicePattern: "next.js",
            statusMustNotBe: "confirmed",
          },
          {
            categoryPattern: "authentication",
            choicePattern: "clerk",
            statusMustNotBe: "confirmed",
          },
        ],
        prohibitedBlueprintPatterns: ["the team selected Next.js", "the team selected Clerk"],
        requireAiSection: false,
        expectedReady: true,
        contradictionMustBlock: false,
      },
    },
    {
      id: "incomplete-idea",
      title: "Deliberately incomplete idea",
      initialIdea: "A tool for teams to organize research notes.",
      answers: ["Researchers and analysts are the likely first users."],
      facts: [
        {
          id: "incomplete-problem",
          statement: "Teams lose useful research notes across scattered documents.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "incomplete-user",
          statement: "Researchers and analysts are the likely first users.",
          source: "explicit",
          topic: "users",
        },
      ],
      expectations: {
        requiredFactPatterns: ["research"],
        materialGapTopics: ["mvp-scope", "core-flows"],
        forbiddenGapTopics: [],
        requiredSections: [],
        requiredStackDecisions: [],
        prohibitedBlueprintPatterns: [],
        requireAiSection: false,
        expectedReady: false,
        contradictionMustBlock: false,
      },
    },
    {
      id: "contradictory-answers",
      title: "Contradictory answers must block readiness",
      initialIdea: "A private journal that users can access from multiple devices.",
      answers: [
        "The journal must work across devices and keep entries permanently.",
        "There must be no database, no account, and no sign-in.",
      ],
      facts: [
        {
          id: "contradiction-problem",
          statement: "People need a private journal available across devices.",
          source: "explicit",
          topic: "product-problem",
        },
        {
          id: "contradiction-user",
          statement: "Individuals are the first users.",
          source: "explicit",
          topic: "users",
        },
        {
          id: "contradiction-scope",
          statement: "V1 must create and retrieve journal entries.",
          source: "explicit",
          topic: "mvp-scope",
        },
        {
          id: "contradiction-db-one",
          statement: "Journal entries must persist permanently in a database.",
          source: "explicit",
          topic: "persistence",
        },
        {
          id: "contradiction-db-two",
          statement: "There must be no database and entries may remain only in-memory.",
          source: "explicit",
          topic: "persistence",
        },
        {
          id: "contradiction-auth-one",
          statement: "Users must sign in to access the journal across devices.",
          source: "explicit",
          topic: "authentication",
        },
        {
          id: "contradiction-auth-two",
          statement: "There must be no account or sign-in.",
          source: "explicit",
          topic: "authentication",
        },
      ],
      expectations: {
        requiredFactPatterns: ["permanently", "no database", "sign in", "no account"],
        materialGapTopics: [],
        forbiddenGapTopics: [],
        requiredSections: [],
        requiredStackDecisions: [],
        prohibitedBlueprintPatterns: [],
        requireAiSection: false,
        expectedReady: false,
        contradictionMustBlock: true,
      },
    },
  ],
} as const;

export const AI_QUALITY_EVALUATION_CORPUS: EvaluationCorpus =
  EvaluationCorpusSchema.parse(corpus);
